# Site settings
title: imphocused
description: 'nothing to see here...'
url: 'http://imphocused.github.io/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'William Dixon'
  email: will@imphocused.com
  twitter_username: imphocused
  facebook_username: imphocused
  github_username:  imphocused
  linkedin_username:  imphocused

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-redirect-from

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
